// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:hocusfocus/data/adapter/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(SessionAdapter());
    registerAdapter(TaskAdapter());
    registerAdapter(TaskScheduleTypeAdapter());
    registerAdapter(TimeSegmentAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(SessionAdapter());
    registerAdapter(TaskAdapter());
    registerAdapter(TaskScheduleTypeAdapter());
    registerAdapter(TimeSegmentAdapter());
  }
}
